//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ответы
    {
        public int id_ответа { get; set; }
        public int id_Вопроса { get; set; }
        public string Текст_ответа { get; set; }
        public bool Флаг_правильного_ответа { get; set; }
    
        public virtual Вопросы Вопросы { get; set; }
    }
}
