//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Результат_теста
    {
        public int id_результата_теста { get; set; }
        public Nullable<System.DateTime> Дата_сдачи_теории { get; set; }
        public Nullable<int> Оценка_за_теорию { get; set; }
        public int id_Теста { get; set; }
        public int id_Общего_результата { get; set; }
        public int id_User { get; set; }
    
        public virtual Общий_результат Общий_результат { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Тесты Тесты { get; set; }
    }
}
