//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тесты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Тесты()
        {
            this.Вопросы = new HashSet<Вопросы>();
            this.Результат_теста = new HashSet<Результат_теста>();
        }
    
        public int id_теста { get; set; }
        public string Название_теста { get; set; }
        public int Количество_вопросов { get; set; }
        public int id_Темы { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Вопросы> Вопросы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Результат_теста> Результат_теста { get; set; }
        public virtual Темы Темы { get; set; }
    }
}
